lesElections/lesElections/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vote/',include ('vote.urls'))
]

lesElections/vote/urls.py
from django.urls import path
from . import views

app_name = 'vote'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:idIdees>/', views.detail, name='detail'),
    path('<int:idIdees>/results', views.results, name='results'),
    path('<int:idIdees>/vote', views.vote, name='vote'),
]

lesElections/vote/models.py
from django.db import models

# Create your models here.
class Penseur(models.Model):
    pseudoPenseur = models.CharField(max_length=60)

    def __str__(self):
        return self.pseudoPenseur

class Idees(models.Model):
    nomIdee = models.CharField(max_length=60)
    typeIdee = models.CharField(max_length=60)
    dateIdee = models.DateTimeField('Date de création de l\'idée')
    penseur = models.ForeignKey(Penseur, on_delete=models.CASCADE)

    def __str__(self):
        return self.nomIdee

class Chevelure(models.Model):
    typeChevelure = models.CharField(max_length=60)
    tailleChevelure = models.IntegerField(default=0)

    def __str__(self):
        return self.typeChevelure

class Roles(models.Model):
    nomRole = models.CharField(max_length=60)
    nbVoteRole = models.IntegerField(default=1)

    def __str__(self):
        return self.nomRole

class Votants(models.Model):
    nomVotant = models.CharField(max_length=60)
    prenomVotant = models.CharField(max_length=60)
    mailVotant = models.CharField(max_length=100)
    voteVotant = models.BooleanField(default=False)
    chevelure = models.ForeignKey(Chevelure, on_delete=models.CASCADE)
    roles = models.ForeignKey(Roles, on_delete=models.CASCADE)
    idees =  models.ManyToManyField(Idees, through='Voter')

    def __str__(self):
        return self.nomVotant, self.prenomVotant

class Voter(models.Model):
    nbVote = models.IntegerField(default=0)
    idees = models.ForeignKey(Idees, on_delete=models.CASCADE)
    votants = models.ForeignKey(Votants, on_delete=models.CASCADE)

    def __str__(self):
        return self.nbVote

lesElections/vote/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Idees
# Create your views here.
def index(request):
    choixIdees = Idees.objects.order_by('dateIdee')
    context = {'listIdees': choixIdees}
    return render(request, 'vote/index.html',context)

def detail(request):
    idee = get_obj_or_404(Idees, pk=idIdees)
    return render(request, 'vote/detail.html', {'idees': idee})

lesElections/vote/templates/vote/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vote</title>
</head>
<body>
    <h1 style="color:blue">Question numéro {{question.id}}</h1>
    <form action="{% url 'vote:vote' idees.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{idees.nomIdee}}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
</body>
</html>

lesElections/vote/templates/vote/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vote</title>
</head>
<body>
    {% if question_list %}
        <ul>
            {% for question in question_list %}
            <li>
                <a href="{% url 'vote:detail' idees.id %}">{{ idees.nomIdee }}</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Pas d'idées  (ﾉಠдಠ)ﾉ︵┻━┻ .</p>
    {% endif %}
</body>
</html>